'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle2, CreditCard, Loader2, LockKeyhole, Truck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useCart } from '@/components/cart/cart-provider'
import { useAuth } from '@/components/auth/auth-provider'
import { AuthDialog } from '@/components/auth/auth-dialog'
import { addOrder, type DemoOrder } from '@/lib/demo-store'
import { formatSom } from '@/lib/data'

export function CheckoutClient() {
 const router=useRouter(); const {user}=useAuth(); const {items,getProductById,cartTotal,clearCart}=useCart(); const [payment,setPayment]=useState('card'); const [loading,setLoading]=useState(false); const [paid,setPaid]=useState(false)
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); if(!user)return; setLoading(true); const data=new FormData(e.currentTarget); setTimeout(()=>{const order:DemoOrder={id:`ES-${Date.now().toString().slice(-8)}`,userId:user.id,customer:String(data.get('name')),phone:String(data.get('phone')),address:String(data.get('address')),items:items.flatMap(i=>{const p=getProductById(i.id);return p?[{id:p.id,name:p.name,price:p.price,quantity:i.quantity}]:[]}),total:cartTotal,payment,status:'Кабыл алынды',createdAt:new Date().toISOString()};addOrder(order);clearCart();setLoading(false);setPaid(true);setTimeout(()=>router.push(`/invoice/${order.id}`),900)},1400)}
 if(paid)return <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 text-center"><CheckCircle2 className="size-16 text-primary"/><h1 className="font-mono text-3xl font-bold uppercase">Төлөм ийгиликтүү</h1><p className="text-muted-foreground">Электрондук чек даярдалууда...</p></div>
 if(!items.length)return <div className="container-px mx-auto max-w-3xl py-24 text-center"><h1 className="font-mono text-3xl font-bold uppercase">Себет бош</h1><Button className="mt-6" onClick={()=>router.push('/catalog')}>Каталогго өтүү</Button></div>
 if(!user)return <div className="container-px mx-auto max-w-xl py-24 text-center"><LockKeyhole className="mx-auto size-12 text-primary"/><h1 className="mt-4 font-mono text-3xl font-bold uppercase">Заказ үчүн кириңиз</h1><p className="my-5 text-muted-foreground">Заказ тарыхын жана чекти сактоо үчүн аккаунт керек.</p><AuthDialog><Button>Кирүү же катталуу</Button></AuthDialog></div>
 return <div className="container-px mx-auto max-w-6xl py-10"><h1 className="mb-8 font-mono text-4xl font-bold uppercase">Заказды даярдоо</h1><form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_380px]"><div className="flex flex-col gap-6"><Section title="1. Алуучунун маалыматы"><div className="grid gap-4 sm:grid-cols-2"><Field label="Аты-жөнү" name="name" defaultValue={user.name}/><Field label="Телефон" name="phone" defaultValue={user.phone}/></div><Field label="Жеткирүү дареги" name="address" placeholder="Шаар, көчө, үй"/></Section><Section title="2. Төлөм ыкмасы"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setPayment('card')} className={`rounded-xl border p-4 text-left ${payment==='card'?'border-primary bg-primary/5':''}`}><CreditCard className="mb-3 size-5 text-primary"/><b>Банк картасы</b><p className="text-sm text-muted-foreground">Демо онлайн төлөм</p></button><button type="button" onClick={()=>setPayment('cash')} className={`rounded-xl border p-4 text-left ${payment==='cash'?'border-primary bg-primary/5':''}`}><Truck className="mb-3 size-5 text-primary"/><b>Алганда төлөө</b><p className="text-sm text-muted-foreground">Накталай же QR</p></button></div>{payment==='card'&&<div className="grid gap-4 rounded-xl bg-secondary p-4 sm:grid-cols-2"><Field label="Карта номери" name="card" placeholder="4242 4242 4242 4242" pattern="[0-9 ]{19}"/><Field label="Карта ээси" name="holder" placeholder="ATY JONU"/><Field label="Мөөнөтү" name="expiry" placeholder="12/29"/><Field label="CVC" name="cvc" placeholder="123" pattern="[0-9]{3}"/></div>}</Section></div><aside className="h-fit rounded-2xl border bg-card p-5"><h2 className="font-mono text-xl font-bold uppercase">Сиздин заказ</h2><div className="my-5 flex flex-col gap-3">{items.map(i=>{const p=getProductById(i.id);return p?<div key={i.id} className="flex justify-between gap-4 text-sm"><span>{p.name} × {i.quantity}</span><b>{formatSom(p.price*i.quantity)}</b></div>:null})}</div><div className="flex justify-between border-t pt-4 text-lg"><span>Жалпы</span><b className="text-primary">{formatSom(cartTotal)}</b></div><Button size="lg" className="mt-5 w-full" disabled={loading}>{loading?<><Loader2 data-icon="inline-start" className="animate-spin"/>Иштетилүүдө...</>:payment==='card'?'Төлөө':'Заказ берүү'}</Button><p className="mt-3 text-center text-xs text-muted-foreground"><LockKeyhole className="mr-1 inline size-3"/>Бул демо, чыныгы акча алынбайт</p></aside></form></div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="flex flex-col gap-5 rounded-2xl border bg-card p-5"><h2 className="font-mono text-xl font-bold uppercase">{title}</h2>{children}</section>}
function Field({label,name,...props}:{label:string;name:string;[key:string]:unknown}){return <div className="flex flex-col gap-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} required {...props}/></div>}
