import Link from 'next/link'
import Image from 'next/image'
import { notFound, redirect } from 'next/navigation'
import { Mail, MapPin, Phone } from 'lucide-react'
import { SiteShell } from '@/components/site/site-shell'
import { Button } from '@/components/ui/button'
import { brands, categories, news } from '@/lib/data'
import { contact } from '@/lib/nav'
const pages:Record<string,{title:string;kicker:string;body:string[]}>= {
 about:{title:'Биз жөнүндө',kicker:'2009-жылдан бери профессионалдар менен',body:['ELTOY STROY — Кыргызстандагы курулуш шаймандарынын ишенимдүү жеткирүүчүсү. Биз түп нуска товарларды расмий кепилдик менен сунуштайбыз.','Бишкек жана Ош шаарларындагы складдарыбызда 12 000ден ашык позиция бар. Адистерибиз ар бир долбоор үчүн туура шайман тандоого жардам берет.']},
 delivery:{title:'Жеткирүү',kicker:'Кыргызстандын бардык аймактарына',body:['Бишкек ичинде 10 000 сомдон жогору заказ акысыз жана 24 саат ичинде жеткирилет. Региондорго 1–3 жумуш күнүндө ишенимдүү карго кызматтары аркылуу жөнөтөбүз.','Заказ даяр болгондо менеджер байланышып, жеткирүү убактысын тактайт. Товарды алууда бүтүндүгүн текшериңиз.']},
 payment:{title:'Төлөм',kicker:'Сизге ыңгайлуу ыкманы тандаңыз',body:['Накталай, Visa/Mastercard банк картасы, QR жана банктык которуу аркылуу төлөөгө болот. Онлайн карта төлөмү бул версияда коопсуз демо катары иштейт жана чыныгы акча алынбайт.','Юридикалык жактар үчүн эсеп-фактура жана коштоочу документтер даярдалат.']},
 warranty:{title:'Кепилдик',kicker:'Түп нуска сапат — расмий колдоо',body:['Ар бир товарга өндүрүүчүнүн 12–36 айлык расмий кепилдиги берилет. Чекти жана кепилдик талонун сактаңыз.','Кепилдик учурунда диагностика расмий сервис борборунда жүргүзүлөт. Өндүрүштүк кемчилик аныкталса, товар оңдолот же алмаштырылат.']},
 contact:{title:'Байланыш',kicker:'Сурооңуз барбы? Биз жардам беребиз',body:['Шоурумда товарларды көрүп, эксперттен кеңеш алып, заказды ошол жерден алып кетсеңиз болот.','Биз дүйшөмбүдөн ишембиге чейин 09:00–19:00 иштейбиз.']}
}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==='new')redirect('/catalog?filter=new');if(slug==='sales')redirect('/catalog?filter=sale');if(slug==='payment-info')redirect('/payment');if(slug==='contacts')redirect('/contact');if(slug==='categories')return <SiteShell><Listing title="Категориялар">{categories.map(c=><Link href={`/catalog?category=${c.slug}`} key={c.slug} className="group overflow-hidden rounded-2xl border bg-card"><div className="relative aspect-video bg-secondary"><Image src={c.image} alt={c.name} fill className="object-contain p-4"/></div><div className="p-5"><h2 className="font-mono text-xl font-bold uppercase group-hover:text-primary">{c.name}</h2><p className="mt-2 text-sm text-muted-foreground">{c.description}</p></div></Link>)}</Listing></SiteShell>;if(slug==='brands')return <SiteShell><Listing title="Дүйнөлүк бренддер">{brands.map(b=><Link href={`/catalog?brand=${b.slug}`} key={b.slug} className="rounded-2xl border bg-card p-6 hover:border-primary"><h2 className="font-mono text-2xl font-bold uppercase">{b.name}</h2><p className="text-muted-foreground">{b.country} · {b.productCount} товар</p></Link>)}</Listing></SiteShell>;if(slug==='news')return <SiteShell><Listing title="Жаңылыктар">{news.map(n=><Link href={`/news/${n.slug}`} key={n.id} className="overflow-hidden rounded-2xl border bg-card"><div className="relative aspect-video bg-secondary"><Image src={n.image} alt={n.title} fill className="object-contain p-4"/></div><div className="p-5"><p className="text-xs text-primary">{n.category} · {n.date}</p><h2 className="mt-2 text-xl font-bold">{n.title}</h2><p className="mt-2 text-sm text-muted-foreground">{n.excerpt}</p></div></Link>)}</Listing></SiteShell>;const page=pages[slug];if(!page)notFound();return <SiteShell><div className="container-px mx-auto max-w-5xl py-16"><p className="font-mono uppercase tracking-widest text-primary">{page.kicker}</p><h1 className="mt-3 text-balance font-mono text-4xl font-bold uppercase md:text-6xl">{page.title}</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><div className="flex flex-col gap-5 text-lg leading-relaxed text-muted-foreground">{page.body.map(x=><p key={x}>{x}</p>)}</div><aside className="flex h-fit flex-col gap-4 rounded-2xl border bg-card p-5"><b>ELTOY STROY</b><p className="flex gap-2 text-sm"><MapPin className="size-4 shrink-0 text-primary"/>{contact.address}</p><a className="flex gap-2 text-sm" href={`tel:${contact.phone}`}><Phone className="size-4 text-primary"/>{contact.phone}</a><a className="flex gap-2 text-sm" href={`mailto:${contact.email}`}><Mail className="size-4 text-primary"/>{contact.email}</a><Button asChild><Link href="/catalog">Каталогду көрүү</Link></Button></aside></div></div></SiteShell>}
function Listing({title,children}:{title:string;children:React.ReactNode}){return <div className="container-px mx-auto max-w-7xl py-12"><h1 className="mb-8 font-mono text-4xl font-bold uppercase md:text-5xl">{title}</h1><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{children}</div></div>}
