'use client'
import { use, useEffect, useState } from 'react'
import Link from 'next/link'
import { Printer } from 'lucide-react'
import { SiteShell } from '@/components/site/site-shell'
import { Button } from '@/components/ui/button'
import { getOrders, type DemoOrder } from '@/lib/demo-store'
import { formatSom } from '@/lib/data'
export default function InvoicePage({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [order,setOrder]=useState<DemoOrder|null>(null);useEffect(()=>setOrder(getOrders().find(o=>o.id===id)||null),[id]);return <SiteShell><div className="container-px mx-auto max-w-3xl py-10">{order?<div className="rounded-3xl border bg-card p-6 md:p-10"><div className="flex items-start justify-between border-b pb-6"><div><p className="font-mono text-2xl font-bold">ELTOY STROY</p><p className="text-sm text-muted-foreground">Электрондук чек</p></div><Button variant="outline" onClick={()=>window.print()}><Printer data-icon="inline-start"/>Басып чыгаруу</Button></div><div className="grid gap-4 py-6 sm:grid-cols-2"><div><p className="text-sm text-muted-foreground">Заказ</p><b>{order.id}</b></div><div><p className="text-sm text-muted-foreground">Дата</p><b>{new Date(order.createdAt).toLocaleString('ky-KG')}</b></div><div><p className="text-sm text-muted-foreground">Кардар</p><b>{order.customer}</b></div><div><p className="text-sm text-muted-foreground">Дарек</p><b>{order.address}</b></div></div><div className="flex flex-col gap-3 border-y py-6">{order.items.map(i=><div key={i.id} className="flex justify-between gap-5"><span>{i.name} × {i.quantity}</span><b>{formatSom(i.price*i.quantity)}</b></div>)}</div><div className="flex justify-between pt-6 text-2xl"><b>Жалпы</b><b className="text-primary">{formatSom(order.total)}</b></div><p className="mt-6 text-sm text-muted-foreground">Статус: {order.status} · Төлөм: {order.payment==='card'?'Карта':'Алганда'}</p></div>:<div className="py-24 text-center"><h1 className="text-2xl font-bold">Чек табылган жок</h1><Button asChild className="mt-5"><Link href="/account">Кабинетке кайтуу</Link></Button></div>}</div></SiteShell>}
